### ISSUE TITLE
Translation English

### ISSUE THREAD

**Issue by rechl** [affilinet/browser-webextension-publisher#1]
https://github.com/affilinet/browser-webextension-publisher/blob/abb44b2f7f72d1f297c6eeeee744c248d62749f2/src/_locales/en/settings-page.js#L166-L173

**Comment by avaffilinet** [comment]
Done https://github.com/affilinet/browser-webextension-publisher/commit/7b476b7b242cb61e1bd3e2c7d91edbb2d6df87b2
