### ISSUE TITLE
Ref not working on share-function "Codes"

### ISSUE THREAD

**Issue by STietze** [affilinet/browser-webextension-publisher#10]
Hi!
A client realized, that the code function "share" creates an invalid link containing a ref value "false".
But at the dialog box the link creation is working properly.
The issue appears across different programs and can be recreated.
Please have a look at the screenshot.

If you have any questions, please feel free to contact me.

Kindly,
Stefan
[Deeplinks Methoden..pdf](https://github.com/affilinet/browser-webextension-publisher/files/1766248/Deeplinks.Methoden.pdf)

**Comment by rechl** [comment]
Just released new version 3.3.3.0. This will fix this issue. 
Will be available in about 1 hour
