### ISSUE TITLE
Tranlsations FR

### ISSUE THREAD

**Issue by rechl** [affilinet/browser-webextension-publisher#2]
https://github.com/affilinet/browser-webextension-publisher/blob/abb44b2f7f72d1f297c6eeeee744c248d62749f2/src/_locales/fr/settings-page.js#L167-L171

**Comment by avaffilinet** [comment]
Done https://github.com/affilinet/browser-webextension-publisher/commit/e5780d106e5d8b4dfbf3385b674880ff29b2515d
