### ISSUE TITLE
Translations ES

### ISSUE THREAD

**Issue by rechl** [affilinet/browser-webextension-publisher#3]
https://github.com/affilinet/browser-webextension-publisher/blob/abb44b2f7f72d1f297c6eeeee744c248d62749f2/src/_locales/es/settings-page.js#L170-L174

**Comment by avaffilinet** [comment]
Done https://github.com/affilinet/browser-webextension-publisher/commit/5c3a92b2734385af0b4f819937e64db283e2074a
