### ISSUE TITLE
Translation NL

### ISSUE THREAD

**Issue by rechl** [affilinet/browser-webextension-publisher#4]
https://github.com/affilinet/browser-webextension-publisher/blob/abb44b2f7f72d1f297c6eeeee744c248d62749f2/src/_locales/nl/settings-page.js#L170-L174

**Comment by avaffilinet** [comment]
Done https://github.com/affilinet/browser-webextension-publisher/commit/d32ac2f0ddbe9146a1de583505e925907cb039cf
