### ISSUE TITLE
Provide updated version

### ISSUE THREAD

**Issue by avaffilinet** [affilinet/browser-webextension-publisher#6]
Bitte aktuelle Version bereitstellen, die die letzten Übersetzungen mit enthält als auch die CSS Anpassung im Widget Code Snippet.

**Comment by rechl** [comment]
Please find the latest version here
https://github.com/affilinet/browser-webextension-publisher/tree/3.3.0.0/dist

**Comment by avaffilinet** [comment]
Ok, will check

**Comment by avaffilinet** [comment]
Widget und Frontend geht.

**Comment by rechl** [comment]
ok will publish new version to extension stores
